{
 "title": "NestJS Application Overview",
 "tags": [ "nestjs" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Heap Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "{{job}} - {{instance}}" }
   ]
  },
  {
   "title": "CPU User Time Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total[1m])",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{job=\"varlogs\"}"
    }
   ]
  }
 ]
}